### ISSUE TITLE
能不能增加一个抓取wskey的功能？

### ISSUE THREAD

**Issue by lukemin** [ZhuSky/JDCookie#1]
能不能增加一个抓取wskey的功能？

**Comment by ZhuSky** [comment]
wskey 是啥 ？ 也是在cookies 中的参数么？

**Comment by lukemin** [comment]
wskey是可以长期使用的，现在的cookie只要登录了京东app就失效。
详见 https://github.com/Zy143L/wskey

**Comment by ZhuSky** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/18596232/159217532-de082fed-bfce-48f1-a9f6-b2a8a3839fd1.png">
你发的这个链接 wskey 是使用方式，没看到具体的获取方式，有其他的获取方式提供借鉴么。
我刚看了一下jd的cookie，没有关于wskey的相关参数

**Comment by ZhuSky** [comment]
@lukemin

**Comment by lukemin** [comment]
> @lukemin

https://blog.csdn.net/u012954039/article/details/120178959

**Comment by ZhuSky** [comment]
好的 ，我看一下，如果可以的话，我今天会更新app

**Comment by ZhuSky** [comment]
@lukemin 您通过这个帖子成功获取wskey 了吗？

**Comment by lukemin** [comment]
![微信图片_20220321162326](https://user-images.githubusercontent.com/12003375/159225840-d9c3bae1-95d2-4081-8be2-f3952fe29c7b.jpg)
我现在用的小黄鸟，效果应该是一样的

**Comment by ZhuSky** [comment]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/18596232/159243118-e0c5af87-c422-40bc-9868-e2bdf88924e8.png">
有点难搞，我抓出来的都是这样的，没找到wskey

**Comment by lukemin** [comment]
看样子wskey只能是京东app里面才有。

**Comment by ZhuSky** [comment]
目前看是的，我在 “京东云无限宝” 上也能抓到 tpt字段 跟wskey一样

**Comment by ZhuSky** [comment]
如果是只有app能获取，那我这目前是不行的

**Comment by lukemin** [comment]
谢谢
